login: &login
  access_key_id: AKIAI4C63C6S2LO7IJ2Q
  secret_access_key: AKIAI4C63C6S2LO7IJ2Q

development:
  bucket_name: 
  <<: *login
  distribution_domain: 

test:
  bucket_name:
  <<: *login
  distribution_domain: 

production: 
  bucket_name: xxx14b4
  <<: *login
  distribution_domain: d2e00nn24ouemb.cloudfront.net
