login: &login
  access_key_id: AKIAI4C63C6S2LO7IJ2Q
  secret_access_key: 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

development:
  bucket_name: xxx14b4
  <<: *login
  distribution_domain: d2e00nn24ouemb.cloudfront.net

test:
  bucket_name: xxx14b4
  <<: *login
  distribution_domain: d2e00nn24ouemb.cloudfront.net

production: 
  bucket_name: xxx14b4
  <<: *login
  distribution_domain: d2e00nn24ouemb.cloudfront.net
